
<div align="center">
<img src ='Pic/logo.png' width='200px'>
    
## KHÓA HỌC: LẬP TRÌNH PYTHON CƠ BẢN CHO PHÂN TÍCH DỮ LIỆU VÀ HỌC MÁY
# Bài 5 - Xử lý dữ liệu số với Thư viện NumPy - Phần 02
</div>

----
Practice 5 - Xử lý dữ liệu số với Thư viện NumPy - Phần 02

---

1. Họ tên học viên: Nguyễn Anh Tú
2. Ngày sinh: 06/10/2006
3. Email: anhtunguyen6106@gmail.com

## THỰC HÀNH SỐ 1:
---
**Yêu cầu: Tạo một vector gồm 30 phần tử, có giá trị tăng dần từ 1 đến 30**

Chỉ sử dụng các phương thức reshape, ravel, split…tách Vector a ở trên thành 3 vector con bao gồm:

1. a_lẻ: chứa các phần tử là số lẻ;
2. a_chan: chứa các phần tử là số chẵn.
3. a_3: chứa các phần tử chia hết cho 3

In [45]:
import numpy as np

In [46]:
#{HỌC VIÊN VIẾT CODE VÀO ĐÂY}

a = np.arange(1, 31)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [47]:
a_le = a.ravel()[a.ravel() % 2 != 0]     # số lẻ
a_chan = a.ravel()[a.ravel() % 2 == 0]   # số chẵn
a_3 = a.ravel()[a.ravel() % 3 == 0]      # chia hết cho 3

print("a_lẻ:", a_le)
print("a_chẵn:", a_chan)
print("a_3:", a_3)

a_lẻ: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
a_chẵn: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
a_3: [ 3  6  9 12 15 18 21 24 27 30]


# THỰC HÀNH SỐ 2:
---

**Yêu cầu 2.1: Đọc dữ liệu từ file Data_Excercise/Data_BMI.txt vào 2 vector tương ứng**
1. v_height: chứa dữ liệu chiều cao
2. v_Weight: Chứa dữ liệu cân nặng


In [48]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [49]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

path= '/content/drive/MyDrive/for_student/Bai5/ThucHanh/Data_Excercise/Data_BMI.txt'

data = np.loadtxt(path)

v_height = data[:, 0]
v_weight = data[:, 1]

print("Chiều cao:", v_height)
print("Cân nặng:", v_weight)


Chiều cao: [174. 189. 185. 195. 149. 189. 147. 154. 174. 169. 195. 159. 192. 155.
 191. 153. 157. 140. 144. 172. 157. 153. 169. 185. 172. 151. 190. 187.
 163. 179. 153. 178. 195. 160. 157. 189. 197. 144. 171. 185. 175. 149.
 157. 161. 182. 185. 188. 181. 161. 140. 168. 176. 163. 172. 196. 187.
 172. 178. 164. 143. 191. 141. 193. 190. 175. 179. 172. 168. 164. 194.
 153. 178. 141. 180. 185. 197. 165. 168. 176. 181. 164. 166. 190. 186.
 168. 198. 175. 145. 159. 185. 178. 183. 194. 177. 197. 170. 142. 160.
 195. 190.]
Cân nặng: [ 96.  87. 110. 104.  61. 104.  92. 111.  90. 103.  81.  80. 101.  51.
  79. 107. 110. 129. 145. 139. 110. 149.  97. 139.  67.  64.  95.  62.
 159. 152. 121.  52.  65. 131. 153. 132. 114.  80. 152.  81. 120. 108.
  56. 118. 126.  76. 122. 111.  72. 152. 135.  54. 110. 105. 116.  89.
  92. 127.  70.  88.  54. 143.  54.  83. 135. 158.  96.  59.  82. 136.
  51. 117.  80.  75. 100. 154. 104.  90. 122.  51.  75. 140. 105. 118.
 123.  50. 141. 117. 104. 140. 154.  96. 111

**Yêu cầu 2.2: Tạo vector v_height_m2 từ vector v_height theo yêu cầu sau:**
1. Chuyển đổi đơn vị của các phần tử từ cm sang m
2. Tính bình phương giá trị các phần tử

In [50]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

v_height_m2 = (v_height/100)**2
print("Chiều cao (m^2):", v_height_m2)





Chiều cao (m^2): [3.0276 3.5721 3.4225 3.8025 2.2201 3.5721 2.1609 2.3716 3.0276 2.8561
 3.8025 2.5281 3.6864 2.4025 3.6481 2.3409 2.4649 1.96   2.0736 2.9584
 2.4649 2.3409 2.8561 3.4225 2.9584 2.2801 3.61   3.4969 2.6569 3.2041
 2.3409 3.1684 3.8025 2.56   2.4649 3.5721 3.8809 2.0736 2.9241 3.4225
 3.0625 2.2201 2.4649 2.5921 3.3124 3.4225 3.5344 3.2761 2.5921 1.96
 2.8224 3.0976 2.6569 2.9584 3.8416 3.4969 2.9584 3.1684 2.6896 2.0449
 3.6481 1.9881 3.7249 3.61   3.0625 3.2041 2.9584 2.8224 2.6896 3.7636
 2.3409 3.1684 1.9881 3.24   3.4225 3.8809 2.7225 2.8224 3.0976 3.2761
 2.6896 2.7556 3.61   3.4596 2.8224 3.9204 3.0625 2.1025 2.5281 3.4225
 3.1684 3.3489 3.7636 3.1329 3.8809 2.89   2.0164 2.56   3.8025 3.61  ]


**Yêu cầu 2.3: Tính chỉ số BMI của 100 người ngày theo công thức bên dưới, chỉ số BMI được làm tròn tới 1 số sau dấu “,”. Lưu kết quả vào vector v_bmi**

In [51]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

v_bmi=v_weight/v_height_m2

v_bmi = np.round(v_bmi, 1)

print("Chỉ số BMI:", v_bmi)




Chỉ số BMI: [31.7 24.4 32.1 27.4 27.5 29.1 42.6 46.8 29.7 36.1 21.3 31.6 27.4 21.2
 21.7 45.7 44.6 65.8 69.9 47.  44.6 63.7 34.  40.6 22.6 28.1 26.3 17.7
 59.8 47.4 51.7 16.4 17.1 51.2 62.1 37.  29.4 38.6 52.  23.7 39.2 48.6
 22.7 45.5 38.  22.2 34.5 33.9 27.8 77.6 47.8 17.4 41.4 35.5 30.2 25.5
 31.1 40.1 26.  43.  14.8 71.9 14.5 23.  44.1 49.3 32.4 20.9 30.5 36.1
 21.8 36.9 40.2 23.1 29.2 39.7 38.2 31.9 39.4 15.6 27.9 50.8 29.1 34.1
 43.6 12.8 46.  55.6 41.1 40.9 48.6 28.7 29.5 19.5 30.7 54.  34.2 54.3
 18.1 13.9]


**Yêu cầu 2.4: Sắp xếp thứ tự các phần tử trong vector v_bmi theo chiều tăng dần, giảm dần**

In [52]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

v_bmi_tang = np.sort(v_bmi)

v_bmi_giam = np.sort(v_bmi)[::-1]

print("BMI tăng dần:", v_bmi_tang)
print("BMI giảm dần:", v_bmi_giam)





BMI tăng dần: [12.8 13.9 14.5 14.8 15.6 16.4 17.1 17.4 17.7 18.1 19.5 20.9 21.2 21.3
 21.7 21.8 22.2 22.6 22.7 23.  23.1 23.7 24.4 25.5 26.  26.3 27.4 27.4
 27.5 27.8 27.9 28.1 28.7 29.1 29.1 29.2 29.4 29.5 29.7 30.2 30.5 30.7
 31.1 31.6 31.7 31.9 32.1 32.4 33.9 34.  34.1 34.2 34.5 35.5 36.1 36.1
 36.9 37.  38.  38.2 38.6 39.2 39.4 39.7 40.1 40.2 40.6 40.9 41.1 41.4
 42.6 43.  43.6 44.1 44.6 44.6 45.5 45.7 46.  46.8 47.  47.4 47.8 48.6
 48.6 49.3 50.8 51.2 51.7 52.  54.  54.3 55.6 59.8 62.1 63.7 65.8 69.9
 71.9 77.6]
BMI giảm dần: [77.6 71.9 69.9 65.8 63.7 62.1 59.8 55.6 54.3 54.  52.  51.7 51.2 50.8
 49.3 48.6 48.6 47.8 47.4 47.  46.8 46.  45.7 45.5 44.6 44.6 44.1 43.6
 43.  42.6 41.4 41.1 40.9 40.6 40.2 40.1 39.7 39.4 39.2 38.6 38.2 38.
 37.  36.9 36.1 36.1 35.5 34.5 34.2 34.1 34.  33.9 32.4 32.1 31.9 31.7
 31.6 31.1 30.7 30.5 30.2 29.7 29.5 29.4 29.2 29.1 29.1 28.7 28.1 27.9
 27.8 27.5 27.4 27.4 26.3 26.  25.5 24.4 23.7 23.1 23.  22.7 22.6 22.2
 21.8 21.7 21.3 21.2 20.9 19.5 18.1 17

**Yêu cầu 2.5: Thống kê số lượng người theo từng mức dựa vào phân loại theo hình**

In [53]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

import pandas as pd


underweight = np.sum(v_bmi < 18.5)
normal = np.sum((v_bmi >= 18.5) & (v_bmi < 25))
overweight = np.sum((v_bmi >= 25) & (v_bmi < 30))
obese = np.sum((v_bmi >= 30) & (v_bmi < 35))
extremely_obese = np.sum(v_bmi >= 35)

bmi_stats = pd.DataFrame({
    'Phân loại': ['Underweight', 'Normal', 'Overweight', 'Obese', 'Extremely Obese'],
    'Số lượng': [underweight, normal, overweight, obese, extremely_obese]
})

print(bmi_stats)
print("Tổng số:", len(v_bmi))




         Phân loại  Số lượng
0      Underweight        10
1           Normal        13
2       Overweight        16
3            Obese        14
4  Extremely Obese        47
Tổng số: 100


## THỰC HÀNH SỐ 3:
---
**Yêu cầu 3.1: Sử dụng vector_weigth trong bài thực hành 2 chuyển về ma trận kích thước 10 x 10**

In [54]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

v_weight_reshape = v_weight.reshape(10,10)

print(v_weight_reshape)


[[ 96.  87. 110. 104.  61. 104.  92. 111.  90. 103.]
 [ 81.  80. 101.  51.  79. 107. 110. 129. 145. 139.]
 [110. 149.  97. 139.  67.  64.  95.  62. 159. 152.]
 [121.  52.  65. 131. 153. 132. 114.  80. 152.  81.]
 [120. 108.  56. 118. 126.  76. 122. 111.  72. 152.]
 [135.  54. 110. 105. 116.  89.  92. 127.  70.  88.]
 [ 54. 143.  54.  83. 135. 158.  96.  59.  82. 136.]
 [ 51. 117.  80.  75. 100. 154. 104.  90. 122.  51.]
 [ 75. 140. 105. 118. 123.  50. 141. 117. 104. 140.]
 [154.  96. 111.  61. 119. 156.  69. 139.  69.  50.]]


**Yêu cầu 3.2: Cho biết ma trận weight có tồn tại ma trân nghịch đảo không? Nếu có hãy xác định ma trận weight-1 ?**

In [55]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

det = np.linalg.det(v_weight_reshape)
print("Định thức =", det)
if det != 0:
    print("Ma trận có nghịch đảo.")
    weight_inv = np.linalg.inv(v_weight_reshape)
    print("Ma trận nghịch đảo weight⁻¹ =\n", weight_inv)
else:
    print("Ma trận không có nghịch đảo .")





Định thức = -1.241241152184681e+18
Ma trận có nghịch đảo.
Ma trận nghịch đảo weight⁻¹ =
 [[ 0.20672933 -0.01828619 -0.08121229  0.15165329 -0.05867193 -0.32128926
   0.00328234 -0.21117582  0.1531515   0.14765915]
 [-0.03378959 -0.00092993  0.01637303 -0.02576189  0.01204942  0.03860094
  -0.00254169  0.0334947  -0.01916893 -0.01399406]
 [ 0.16001186 -0.01361912 -0.06334124  0.11206935 -0.06692393 -0.2278292
   0.01233269 -0.16357827  0.12566149  0.10512262]
 [-0.20060155  0.0096163   0.08597968 -0.14951455  0.06703284  0.32178178
  -0.00847147  0.21237844 -0.160284   -0.14756298]
 [-0.1151341   0.00896286  0.04087891 -0.07066568  0.02398925  0.16297821
   0.00236627  0.09744888 -0.06997591 -0.06720453]
 [ 0.04172982 -0.00327195 -0.01645048  0.02463278 -0.00963244 -0.05248791
   0.0053399  -0.03159687  0.01832677  0.02128759]
 [ 0.46636016 -0.03988045 -0.19342132  0.33291136 -0.13479078 -0.70496996
   0.01080126 -0.45280827  0.34838493  0.30636839]
 [-0.35820439  0.03342262  0.14250743

**Yêu cầu 3.3: Tạo vector_diagonal chứa các phần tử trên đường chéo chính của ma trận weight, tính trace của ma trận weight.**

In [56]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

vector_diagonal = np.diagonal(v_weight_reshape)

trace_weight = np.trace(v_weight_reshape)

print("Vector đường chéo chính:", vector_diagonal)
print("Trace của ma trận weight:", trace_weight)



Vector đường chéo chính: [ 96.  80.  97. 131. 126.  89.  96.  90. 104.  50.]
Trace của ma trận weight: 959.0


**Yêu cầu 3.4: Tìm giá trị lớn nhất, nhỏ nhất của ma trận đường chéo trên và ma trận đường chéo dưới không bao gồm các phần tử trên đường chéo chính**

In [57]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

vector_diagonal_below = np.diagonal(v_weight_reshape, offset=-1)

max_diagonal = np.max(vector_diagonal)
min_diagonal = np.min(vector_diagonal)

max_diagonal_below = np.max(vector_diagonal_below)
min_diagonal_below = np.min(vector_diagonal_below)

print("Đường chéo chính:", vector_diagonal)
print("Giá trị lớn nhất trên đường chéo chính:", max_diagonal)
print("Giá trị nhỏ nhất trên đường chéo chính:", min_diagonal)

print("Đường chéo dưới:", vector_diagonal_below)
print("Giá trị lớn nhất trên đường chéo dưới:", max_diagonal_below)
print("Giá trị nhỏ nhất trên đường chéo dưới:", min_diagonal_below)





Đường chéo chính: [ 96.  80.  97. 131. 126.  89.  96.  90. 104.  50.]
Giá trị lớn nhất trên đường chéo chính: 131.0
Giá trị nhỏ nhất trên đường chéo chính: 50.0
Đường chéo dưới: [ 81. 149.  65. 118. 116. 158. 104. 117.  69.]
Giá trị lớn nhất trên đường chéo dưới: 158.0
Giá trị nhỏ nhất trên đường chéo dưới: 65.0


# THỰC HÀNH SỐ 4
---
**Yêu cầu 4.1: Chuyển vector_height, vector_weigth trong bài thực hành 2 về ma trận height, weight kích thước 10 x 10.**

Thực hiện các phép toán: So sánh; Cộng; Trừ; Nhân hai ma trận height và weighT

In [58]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

height = v_height.reshape(10, 10)
weight = v_weight.reshape(10, 10)






In [59]:
comparison = height > weight
print("Ma trận so sánh (height > weight):\n", comparison)


Ma trận so sánh (height > weight):
 [[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [60]:
sum_matrix = height + weight
print("Ma trận tổng:\n", sum_matrix)

Ma trận tổng:
 [[270. 276. 295. 299. 210. 293. 239. 265. 264. 272.]
 [276. 239. 293. 206. 270. 260. 267. 269. 289. 311.]
 [267. 302. 266. 324. 239. 215. 285. 249. 322. 331.]
 [274. 230. 260. 291. 310. 321. 311. 224. 323. 266.]
 [295. 257. 213. 279. 308. 261. 310. 292. 233. 292.]
 [303. 230. 273. 277. 312. 276. 264. 305. 234. 231.]
 [245. 284. 247. 273. 310. 337. 268. 227. 246. 330.]
 [204. 295. 221. 255. 285. 351. 269. 258. 298. 232.]
 [239. 306. 295. 304. 291. 248. 316. 262. 263. 325.]
 [332. 279. 305. 238. 316. 326. 211. 299. 264. 240.]]


In [61]:
diff_matrix = height - weight
print("Ma trận hiệu:\n", diff_matrix)

Ma trận hiệu:
 [[ 78. 102.  75.  91.  88.  85.  55.  43.  84.  66.]
 [114.  79.  91. 104. 112.  46.  47.  11.  -1.  33.]
 [ 47.   4.  72.  46. 105.  87.  95. 125.   4.  27.]
 [ 32. 126. 130.  29.   4.  57.  83.  64.  19. 104.]
 [ 55.  41. 101.  43.  56. 109.  66.  70.  89. -12.]
 [ 33. 122.  53.  67.  80.  98.  80.  51.  94.  55.]
 [137.  -2. 139. 107.  40.  21.  76. 109.  82.  58.]
 [102.  61.  61. 105.  85.  43.  61.  78.  54. 130.]
 [ 89.  26.  85.  68.  45. 148.  34.  28.  55.  45.]
 [ 24.  87.  83. 116.  78.  14.  73.  21. 126. 140.]]


## THỰC HÀNH SỐ 5
---
**Yêu cầu: Học viên tìm ma trận nghịch đảo và hạng của ma trận Height, Weight trong bài thực hành số 4:**


In [62]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}

def check(matrix, name):
    if matrix.shape[0] == matrix.shape[1]:
      det = np.linalg.det(matrix)
      print(f"Định thức của ma trận {name}: {det}")
      if det != 0:
          inv_matrix = np.linalg.inv(matrix)
          print(f" Ma trận {name} có nghịch đảo:\n", inv_matrix)
      else:
          print(f" Ma trận {name} không có nghịch đảo (det = 0).")


check(height, "Height")
check(weight, "Weight")




Định thức của ma trận Height: -4.407407039044561e+16
 Ma trận Height có nghịch đảo:
 [[ 0.01603724  0.02092798  0.0005634  -0.01423585  0.03551657 -0.04363049
  -0.01948489  0.00700362  0.00206303 -0.00199753]
 [ 0.01145501  0.01012574 -0.00177983  0.01702373 -0.02926175  0.02637695
   0.00593858  0.00934035 -0.03106974 -0.01725456]
 [-0.00829272 -0.01629126 -0.01300203  0.02597273 -0.04412866  0.0594086
   0.04409162 -0.02043952 -0.02539402 -0.00393563]
 [ 0.01044593  0.00900932  0.03553735 -0.06072899  0.06619758 -0.08123257
  -0.08346583 -0.01149921  0.0943043   0.02491969]
 [-0.01611873  0.00544315  0.00754171 -0.02223981  0.0163093  -0.01285604
  -0.02944805 -0.00336405  0.03903407  0.0168835 ]
 [-0.00650082 -0.0159626  -0.03003311  0.02587248 -0.03728232  0.0528001
   0.05303036  0.00676435 -0.03283975 -0.01754762]
 [ 0.00220234  0.01502042  0.02576185 -0.02610571  0.06230938 -0.07197318
  -0.06776956 -0.00413956  0.05602876  0.01243454]
 [-0.00569104 -0.02511792 -0.02964712  0.0

In [63]:
rank_height = np.linalg.matrix_rank(height)
rank_weight = np.linalg.matrix_rank(weight)

print("Hạng của ma trận Height:", rank_height)
print("Hạng của ma trận Weight:", rank_weight)

Hạng của ma trận Height: 10
Hạng của ma trận Weight: 10
